### ISSUE TITLE
'Werken met' versus 'Verwerken van'

### ISSUE THREAD

**Issue by folkjur** [holacracyone/Holacracy-Constitution-4.1-DUTCH#4]
Ik vraag mij af of de Nederlandse vertaling van het artikel 1.2.1 van de Grondwet (Werken met Spanningen) waarin gesproken wordt over ‘het oplossen van verschillen’ juist geformuleerd c.q. vertaald is. 
De oorspronkelijke tekst van artikel 1.2.1 heeft het over ‘to resolve those tensions’.  Hier wordt het werkwoord ‘resolve’ gebruikt dat verwijst naar het **verwerken** van veelal emoties. Het werkwoord ‘solve’ wordt in het Engels gebruikt in de context van het **oplossen** van veelal logische problemen (bijv. wiskundige). Aangezien Spanningen meer worden 'gevoeld' dan 'gedacht' (zie o.a. het artikel dat Chris Cowan hierover geschreven heeft), lijkt mij het werkwoord 'verwerken' meer op z'n plaats dan 'oplossen'.

**Comment by imme-emosol** [comment]
Is het niet eerder zo dat 'deze verschillen' in de [Holocratische Grondwet 1.2.1[nl]](https://github.com/holacracyone/Holacracy-Constitution-4.1-DUTCH/blob/master/Holacracy-Grondwet.md#121-werken-met-spanningen) juist weer vertaald zou moeten worden met '**Spanning(en)**'?

In de engelse versie wordt in ieder geval wel 'tension' herbruikt; [Holocracy Constitution 1.2.1[en]](https://github.com/holacracyone/Holacracy-Constitution/blob/v4.1/Holacracy-Constitution.md#121-processing-tensions) .

**Comment by folkjur** [comment]
Een spanning signaleert een verschil (en is dus niet zelf het verschil dat 'opgelost' moet worden) en wordt 'verwerkt' tot iets dat het verschil opheft. In die zin is 'Verwerken van spanningen' mijns inziens een betere vertaling (van 'processing tensions') dan 'Werken met spanningen'.

**Comment by imme-emosol** [comment]
Voor mij is spanning meer een indicator/meetwaarde. Vanuit die opvatting is spanning altijd aanwezig en zul je er dus mee moeten werken, mee om moeten gaan.
Uiteraard varieert voor elke spanning de mate van (negatieve) invloed op de werkzaamheden c.q. rolverantwoordelijkheden. Bij de ene spanning zal rolvervuller meer belang hebben bij verandering dan bij een andere spanning.

De spanning zie ik als het ervaren van een verschil tussen de beleefde huidige realiteit en het bedachte ideale potentieel van een specifieke rol. Het gaat dan ook niet zozeer om het verwerken van een eigen, emotioneel soort spanning maar eerder om het aanpassen van de realiteit of het aanpassen van de eigen opvatting(en) over het ideale potentieel van de rol.

Deze 'upstream'-dialoog lijkt gerelateerd:
- https://github.com/holacracyone/Holacracy-Constitution/issues/102
- https://community.holacracy.org/topic/is-tension-essential-new-vocabulary-or-can-we-use-issue-instead

Misschien zou het beter vertaald kunnen worden door in plaats van de letterlijk tekst, meer de geest van de tekst te vertalen. De titel zou dan bijvoorbeeld worden: 'Werken met verschillen tussen de huidige realiteit en het ideale potentieel'.
Dit zou voorkomen dat er vanuit de tekst gestart wordt met een idee van overspanning, frustratie, gespannen zijn. Een mogelijk meer ludieke vertaling zou kunnen zijn: 'Ontspannen werken' ;)

**Comment by diederickjanse** [comment]
Helemaal eens Folkert, en sorry dat ik niet eerder heb gereageerd. Ik ben bezig met een grondige review van de vereenvoudigde en wat meer vrij vertaalde Nederlandse versie van de Constitution (zie huidige versie hier: https://drive.google.com/open?id=0B1YzLiDplkQxVzlSeVNjaGZNTlU). Daarin worden jullie opmerkingen volgens mij geadresseerd. De review is alleen nog niet af, en daarna moet ik hem verwerken in de volledige Nederlandstalige versie. Maar de term 'spanning' lijkt mij de juiste, ook gezien de acceptatie van die term bij organisaties in NL, en ik ben het met jullie eens dat je een spanning niet 'oplost' maar eerder 'verwerkt', 'behandelt' en/of 'adresseert.' Wordt vervolgd, dus, maar goed om te weten dat er anderen mee kijken naar deze vertaling!
