### ISSUE TITLE
Vertaling volgt niet de "Translation Guidelines"

### ISSUE THREAD

**Issue by setpill** [holacracyone/Holacracy-Constitution-4.1-DUTCH#5]
Met name de instructie dat het vertalingswerk op basis van de 4.1 release tag - en expliciet *NIET* obv de meest recente development versie - dient te gebeuren lijkt mogelijk ongedaan gemaakt te zijn door het feit dat de commit die deze "Translation Guidelines" toevoegt op de toenmalige development versie gebouwd is, ipv direct op de 4.1 tag. Het is mogelijk dat de vertaling van de constitutie/grondwet zelf obv de 4.1 tag gebeurd is - dit heb ik nog niet gecontroleerd, maar de (onvertaalde) appendices bevatten wijzigingen ten opzichte van de 4.1 tag.

**Comment by diederickjanse** [comment]
De vertaling stamt uit de tijd dat er nog geen development versie was, dus als het goed is is de hoofdtekst wel degelijk gebaseerd op 4.1. Ik heb de NL vertaling van de grondwet, incl. de appendices recent herzien en moet dat hier nog doorvoeren, dus ik zal hier even goed op letten!

**Comment by setpill** [comment]
Aan de hand van https://github.com/holacracyone/Holacracy-Constitution-4.1-DUTCH/compare/v4.1...108a79baf32d2eeeb50132e9ba281505f3dacb11 lijkt de NL vertaling van de grondwet inderdaad gebaseerd op de 4.1 tag (zie bijvoorbeeld sectie 1.1, definitie van een rol). Vertaalde appendices (obv 4.1) zie ik graag tegemoet :)
